### ISSUE TITLE
How to get pretrained GAN parameters on custom datasets

### ISSUE THREAD

**Issue by Yearsflow** [VICO-UoE/IT-GAN#2]
Hi,

Thanks for your work. Recently I've been running experiments on custom datasets. However, code cannot be run because it requires pretrained GAN, ConvNet and GAN Inversion parameters. So how can I get pretrained GAN parameters on custom datasets? Would you please share the training process using GAN and GAN Inversion? 

Thanks a lot.

**Comment by PatrickZH** [comment]
Hi, the pretrained GANs are provided in [Google Drive](https://drive.google.com/drive/folders/1qyxK4XxboBRuQVwesxQTSx-Vpcp1fCeS?usp=sharing) in readme.

**Comment by Yearsflow** [comment]
Thank you, I've noticed that. However, I wonder how to get pretrained GAN model parameters on custom datasets. Could you please give me some suggestions?

**Comment by PatrickZH** [comment]
You may need to finetune pre-trained GANs on your custom datasets.

**Comment by Yearsflow** [comment]
Thank you very much. I get it.
